### ISSUE TITLE
Google Game Play services ANE not working

### ISSUE THREAD

**Issue by priyeshsheth** [Laur3nt1u/ANE-Google-Play-Services#1]
Hi,
I have added both ANE in my project(Adobe animate CC) publish with air 21.0.0.150 for android

But nothing happened.

<![CDATA[

</application>

```
        <uses-permission android:name="android.permission.INTERNET"/>
        <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
        <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
        <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

        <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
        <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    </manifest>

]]></manifestAdditions>
```

</android>

com.freshplanet.AirGooglePlayGameServices
com.laurentiu.AirGooglePlayServices

Please help me.. if possible than could you plz send me mail ?
Here is my email id priyesh.j.sheth@gmail.com

**Comment by Laur3nt1u** [comment]
```
<manifest android:installLocation="auto">
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
            <application>

                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
                <activity android:name="com.freshplanet.googleplaygames.SignInActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
                <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ YOUR_APP_ID" />

            </application>
        </manifest>
```

**Comment by swarajcs** [comment]
Hi,

am also having issue with adding google play services to my game.

am using the code.

import com.freshplanet.ane.AirGooglePlayGames.AirGooglePlayGames;
import com.freshplanet.ane.AirGooglePlayGames.AirGooglePlayGamesEvent;
import com.laurentiu.ane.AirGooglePlayServices.AirGooglePlayServices;

```
    AirGooglePlayGames.getInstance().addEventListener(AirGooglePlayGamesEvent.ON_SIGN_IN_SUCCESS, onSignInSuccess);
    AirGooglePlayGames.getInstance().addEventListener(AirGooglePlayGamesEvent.ON_SIGN_OUT_SUCCESS, onSignOutSuccess);
    AirGooglePlayGames.getInstance().addEventListener(AirGooglePlayGamesEvent.ON_SIGN_IN_FAIL, onSignInFail);
```

stage.addEventListener(MouseEvent.MOUSE_DOWN, launch_app_fn);
function launch_app_fn(event:MouseEvent)
{
txt.text = "button clicked ";
try

{

//AirGooglePlayGames.getInstance().isSignedIn();
AirGooglePlayGames.getInstance().signIn();

}catch(err)
{       txt.text = ""+err;
}

}

function onSignInSuccess(event:AirGooglePlayGamesEvent)
{txt.text = "onSignInSuccess ";
}
function onSignOutSuccess(event:AirGooglePlayGamesEvent)
{txt.text = "onSignOutSuccess ";
}
function onSignInFail(event:AirGooglePlayGamesEvent)
{txt.text = "onSignInFail ";
}

it showing error ArgumentError: Error #3500

am using adobe air version 21. Please help me with this issue. Will it only work with version 20 ?

**Comment by Laur3nt1u** [comment]
Do you have other anes in your project?

**Comment by Laur3nt1u** [comment]
Post the whole error message

**Comment by swarajcs** [comment]
"ArgumentError: Error #3500" is the only message am getting as error in try catch error log

try
{
//AirGooglePlayGames.getInstance().isSignedIn();
AirGooglePlayGames.getInstance().signIn();

}catch(err)
{ txt.text = ""+err;
}

}

am displaying the "err" from catch.. 

is there anything wrong in my code?

xml file is 

```
<android>
    <manifestAdditions>
        <![CDATA[<manifest android:installLocation="auto">
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
            <application>
                <activity android:name="com.freshplanet.googleplaygames.SignInActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
                <meta-data android:name="com.google.android.gms.games.APP_ID" android:value="\ appidusedhere" />
                <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
            </application>
        </manifest>]]>
    </manifestAdditions>
  </android>
```

added anes from https://github.com/Laur3nt1u/ANE-Google-Play-Game-Services and 
https://github.com/Laur3nt1u/ANE-Google-Play-Services

what is this for?

cd /path/to/the/ane/build
mv example.build.config build.config
#edit the build.config file to provide your machine-specific paths
ant

Just added ANE , changing xml file and bulding from publish settings. Is there anything else i have to do with that?

**Comment by Laur3nt1u** [comment]
try to get the logcat from android while calling AirGooglePlayGames.getInstance().signIn(); it will show you the problem or post the logcat here

**Comment by swarajcs** [comment]
Thanks for your help, 

 am not sure whether the logcat is correct. This is what I got when opened the app.

test is the name for app . I typed as adb -d logcat test 

This is what the response I got.

I/dalvikvm(29336): Failed resolving Lcom/adobe/air/ActivityResultCallback; inter
face 1596 'Lcom/adobe/air/AndroidActivityWrapper$ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/adobe/air/ActivityResultCallback;' failed

I/dalvikvm(29336): Failed resolving Lcom/freshplanet/googleplaygames/ExtensionCo
ntext; interface 1595 'Lcom/adobe/air/ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/freshplanet/googleplaygames/ExtensionCont
ext;' failed
I/dalvikvm(29336): Failed resolving Lcom/adobe/air/ActivityResultCallback; inter
face 1596 'Lcom/adobe/air/AndroidActivityWrapper$ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/adobe/air/ActivityResultCallback;' failed

I/dalvikvm(29336): Failed resolving Lcom/freshplanet/googleplaygames/ExtensionCo
ntext; interface 1595 'Lcom/adobe/air/ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/freshplanet/googleplaygames/ExtensionCont
ext;' failed
I/dalvikvm(29336): Could not find method com.freshplanet.googleplaygames.Extensi
onContext.dispatchStatusEventAsync, referenced from method com.freshplanet.googl
eplaygames.Extension.log
W/dalvikvm(29336): VFY: unable to resolve virtual method 11650: Lcom/freshplanet
/googleplaygames/ExtensionContext;.dispatchStatusEventAsync (Ljava/lang/String;L
java/lang/String;)V
D/dalvikvm(29336): VFY: replacing opcode 0x6e at 0x0004
I/dalvikvm(29336): Failed resolving Lcom/adobe/air/ActivityResultCallback; inter
face 1596 'Lcom/adobe/air/AndroidActivityWrapper$ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/adobe/air/ActivityResultCallback;' failed

I/dalvikvm(29336): Failed resolving Lcom/freshplanet/googleplaygames/ExtensionCo
ntext; interface 1595 'Lcom/adobe/air/ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/freshplanet/googleplaygames/ExtensionCont
ext;' failed
E/dalvikvm(29336): Could not find class 'com.freshplanet.googleplaygames.Extensi
onContext', referenced from method com.freshplanet.googleplaygames.Extension.cre
ateContext
W/dalvikvm(29336): VFY: unable to resolve new-instance 1617 (Lcom/freshplanet/go
ogleplaygames/ExtensionContext;) in Lcom/freshplanet/googleplaygames/Extension;
D/dalvikvm(29336): VFY: replacing opcode 0x22 at 0x0000
I/dalvikvm(29336): Failed resolving Lcom/adobe/air/ActivityResultCallback; inter
face 1596 'Lcom/adobe/air/AndroidActivityWrapper$ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/adobe/air/ActivityResultCallback;' failed

I/dalvikvm(29336): Failed resolving Lcom/freshplanet/googleplaygames/ExtensionCo
ntext; interface 1595 'Lcom/adobe/air/ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/freshplanet/googleplaygames/ExtensionCont
ext;' failed
I/dalvikvm(29336): Failed resolving Lcom/adobe/air/ActivityResultCallback; inter
face 1596 'Lcom/adobe/air/AndroidActivityWrapper$ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/adobe/air/ActivityResultCallback;' failed

I/dalvikvm(29336): Failed resolving Lcom/freshplanet/googleplaygames/ExtensionCo
ntext; interface 1595 'Lcom/adobe/air/ActivityResultCallback;'
W/dalvikvm(29336): Link of class 'Lcom/freshplanet/googleplaygames/ExtensionCont
ext;' failed
D/dalvikvm(29336): DexOpt: unable to opt direct call 0x2d7e at 0x02 in Lcom/fres
hplanet/googleplaygames/Extension;.createContext
W/System.err(29336): java.lang.NoClassDefFoundError: com.freshplanet.googleplayg
ames.ExtensionContext
W/System.err(29336):    at com.freshplanet.googleplaygames.Extension.createConte
xt(Unknown Source)
W/System.err(29336):    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Met
hod)
W/System.err(29336):    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Met
hod)
W/System.err(29336):    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:
139)
W/System.err(29336):    at com.adobe.air.AndroidActivityWrapper.LaunchApplicatio
n(AndroidActivityWrapper.java:1042)
W/System.err(29336):    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitial
ized(AndroidActivityWrapper.java:1241)
W/System.err(29336):    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIR
WindowSurfaceView.java:747)
W/System.err(29336):    at android.view.SurfaceView.updateWindow(SurfaceView.jav
a:583)
W/System.err(29336):    at android.view.SurfaceView.access$000(SurfaceView.java:
86)
W/System.err(29336):    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java
:175)
W/System.err(29336):    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewT
reeObserver.java:847)
W/System.err(29336):    at android.view.ViewRootImpl.performTraversals(ViewRootI
mpl.java:1897)
W/System.err(29336):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.ja
va:1019)
W/System.err(29336):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewR
ootImpl.java:5725)
W/System.err(29336):    at android.view.Choreographer$CallbackRecord.run(Choreog
rapher.java:761)
W/System.err(29336):    at android.view.Choreographer.doCallbacks(Choreographer.
java:574)
W/System.err(29336):    at android.view.Choreographer.doFrame(Choreographer.java
:544)
W/System.err(29336):    at android.view.Choreographer$FrameDisplayEventReceiver.
run(Choreographer.java:747)
W/System.err(29336):    at android.os.Handler.handleCallback(Handler.java:733)
W/System.err(29336):    at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err(29336):    at android.os.Looper.loop(Looper.java:136)
W/System.err(29336):    at android.app.ActivityThread.main(ActivityThread.java:5
086)
W/System.err(29336):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(29336):    at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err(29336):    at com.android.internal.os.ZygoteInit$MethodAndArgsCalle
r.run(ZygoteInit.java:785)
W/System.err(29336):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.ja
va:601)
W/System.err(29336):    at dalvik.system.NativeStart.main(Native Method)
I/Choreographer(29336): Skipped 101 frames!  The application may be doing too mu
ch work on its main thread.
I/SFPerfTracer(  297):      triggers: (rate: 392:15529) (compose: 0:45) (post: 0
:7) (render: 44:1128) (0:120985 frames) (1:610136)
D/SFPerfTracer(  297):        layers: (4:18) (DimLayer: 0:141)\* (DimLayer: 0:55)
- (FocusedStackFrame: 0:3454)\* (StatusBar: 1:39074) (NavigationBar: 0:27229) (co
  m.android.systemui.ImageWallpaper: 0:1598)\* (ScreenshotSurface: 0:23)\* (com.andr
  oid.launcher/com.android.launcher2.Launcher: 0:28)\* (BlackSurface: 0:22)\* (Black
  Surface: 0:22)\* (BlackSurface: 0:22)\* (BlackSurface: 0:22)\* (Starting air.test:
  0:25) (ScreenshotSurface: 0:2) (air.test/air.test.AppEntry: 0:6)\* (SurfaceView:
  0:6)*

**Comment by swarajcs** [comment]
Is there anything wrong in my code or what am doing ? Is there any other url that I could use for google play services that is working with latest adobe air?

**Comment by Laur3nt1u** [comment]
are you using my fork of [Google Play Game Services](https://github.com/Laur3nt1u/ANE-Google-Play-Game-Services/tree/master/bin) ?

**Comment by swarajcs** [comment]
yes, i am using the same one. is there any issue with the adobe air version ? am using 21. is there anything wrong from logcat?

**Comment by swarajcs** [comment]
am using the same one. is there any option for me to understand, whats the
exact issue?

This is my complete xml file.

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<application xmlns="http://ns.adobe.com/air/application/21.0">
  <id>test1</id>
  <versionNumber>1.0.0</versionNumber>
  <versionLabel/>
  <filename>test1</filename>
  <description/>



  <name>test1</name>



  <copyright/>
  <initialWindow>
    <content>test.swf</content>
    <systemChrome>standard</systemChrome>
    <transparent>false</transparent>
    <visible>true</visible>
    <fullScreen>true</fullScreen>
    <aspectRatio>landscape</aspectRatio>
    <renderMode>gpu</renderMode>
    <autoOrients>false</autoOrients></initialWindow>
  <icon/>
  <customUpdateUI>false</customUpdateUI>
  <allowBrowserInvocation>false</allowBrowserInvocation>
  <android>
    <manifestAdditions>
      <![CDATA[<manifest android:installLocation="auto">
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission
android:name="android.permission.ACCESS_NETWORK_STATE"/>
            <uses-permission
android:name="android.permission.ACCESS_WIFI_STATE"/>
            <uses-permission android:name="android.permission.WAKE_LOCK"/>
            <uses-permission
android:name="android.permission.READ_PHONE_STATE"/>
            <application>
                <activity
android:name="com.freshplanet.googleplaygames.SignInActivity"
android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
                <meta-data
android:name="com.google.android.gms.games.APP_ID" android:value="\
xxxxxxxxxxxx" />
                <meta-data android:name="com.google.android.gms.version"
android:value="@integer/google_play_services_version" />
            </application>
        </manifest>]]>
    </manifestAdditions>
  </android>
  <supportedLanguages>en</supportedLanguages>
  <extensions>
    <extensionID>com.laurentiu.AirGooglePlayServices</extensionID>
    <extensionID>com.freshplanet.AirGooglePlayGameServices</extensionID>
  </extensions>
</application>

will it work with air version 21?

On Fri, Jun 3, 2016 at 12:29 PM, Laur3nt1u notifications@github.com wrote:

> are you using my fork of Google Play Game Services
> https://github.com/Laur3nt1u/ANE-Google-Play-Game-Services/tree/master/bin
> ?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/Laur3nt1u/ANE-Google-Play-Services/issues/1#issuecomment-223505543,
> or mute the thread
> https://github.com/notifications/unsubscribe/APi-bBZvHL81yg66aAj3i4ukuPMgsXbRks5qH9DpgaJpZM4IakM9
> .

## 

_Warm Regards,_

_Swaraj CS_

_Project Manager_

_Infocom Software Pvt Ltd. *
Palarivattom_ |_Cochin 25_ |_India
*|_(Work 91.484.3107000_|_Cell 91.9946850824
_swaraj@icsoft.in hectosh@icsoft.in_ \* |*http:\www.infocomsoft.com

**Comment by swarajcs** [comment]
hi,

   is there any help I could get from anywhere on this? I have to try
anything else ?

On Fri, Jun 3, 2016 at 3:00 PM, Swaraj C.S swaraj@icsoft.in wrote:

> am using the same one. is there any option for me to understand, whats the
> exact issue?
> 
> This is my complete xml file.
> 
> <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
> <application xmlns="http://ns.adobe.com/air/application/21.0">
>   <id>test1</id>
>   <versionNumber>1.0.0</versionNumber>
>   <versionLabel/>
>   <filename>test1</filename>
>   <description/>
> 
> 
> 
>   <name>test1</name>
> 
> 
> 
>   <copyright/>
>   <initialWindow>
>     <content>test.swf</content>
>     <systemChrome>standard</systemChrome>
>     <transparent>false</transparent>
>     <visible>true</visible>
>     <fullScreen>true</fullScreen>
>     <aspectRatio>landscape</aspectRatio>
>     <renderMode>gpu</renderMode>
>     <autoOrients>false</autoOrients></initialWindow>
>   <icon/>
>   <customUpdateUI>false</customUpdateUI>
>   <allowBrowserInvocation>false</allowBrowserInvocation>
>   <android>
>     <manifestAdditions>
>       <![CDATA[<manifest android:installLocation="auto">
>             <uses-permission android:name="android.permission.INTERNET"/>
>             <uses-permission
> android:name="android.permission.ACCESS_NETWORK_STATE"/>
>             <uses-permission
> android:name="android.permission.ACCESS_WIFI_STATE"/>
>             <uses-permission android:name="android.permission.WAKE_LOCK"/>
>             <uses-permission
> android:name="android.permission.READ_PHONE_STATE"/>
>             <application>
>                 <activity
> android:name="com.freshplanet.googleplaygames.SignInActivity"
> android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen" />
>                 <meta-data
> android:name="com.google.android.gms.games.APP_ID" android:value="\
> xxxxxxxxxxxx" />
>                 <meta-data android:name="com.google.android.gms.version"
> android:value="@integer/google_play_services_version" />
>             </application>
>         </manifest>]]>
>     </manifestAdditions>
>   </android>
>   <supportedLanguages>en</supportedLanguages>
>   <extensions>
>     <extensionID>com.laurentiu.AirGooglePlayServices</extensionID>
>     <extensionID>com.freshplanet.AirGooglePlayGameServices</extensionID>
>   </extensions>
> </application>
> 
> will it work with air version 21?
> 
> On Fri, Jun 3, 2016 at 12:29 PM, Laur3nt1u notifications@github.com
> wrote:
> 
> > are you using my fork of Google Play Game Services
> > https://github.com/Laur3nt1u/ANE-Google-Play-Game-Services/tree/master/bin
> > ?
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > https://github.com/Laur3nt1u/ANE-Google-Play-Services/issues/1#issuecomment-223505543,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/APi-bBZvHL81yg66aAj3i4ukuPMgsXbRks5qH9DpgaJpZM4IakM9
> > .
> 
> ## 
> 
> _Warm Regards,_
> 
> _Swaraj CS_
> 
> _Project Manager_
> 
> _Infocom Software Pvt Ltd. *
> Palarivattom_ |_Cochin 25_ |_India
> *|_(Work 91.484.3107000_|_Cell 91.9946850824
> _swaraj@icsoft.in hectosh@icsoft.in_ \* |*http:\www.infocomsoft.com

## 

_Warm Regards,_

_Swaraj CS_

_Project Manager_

_Infocom Software Pvt Ltd. *
Palarivattom_ |_Cochin 25_ |_India
*|_(Work 91.484.3107000_|_Cell 91.9946850824
_swaraj@icsoft.in hectosh@icsoft.in_ \* |*http:\www.infocomsoft.com

**Comment by priyeshsheth** [comment]
Hello guys,

Still not getting any proper result.

When i use that ANE and Update xml as well as code as per direction. but no
result.

I am using adobe animate CC with adobe air 21.

Please, do one thing, could you make one demo project ??

Thanks,
Priyesh Sheth
Alayada.com
